# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Saket's Blog
tagline:          "A Themer's Point of view"
description:      'Technical, Practical, Theoretically Interesting '
url:              http://saki007ster.github.io
baseurl:          /

author:
  name:           'Saket Kumar'
  url:            https://www.drupal.org/u/saki007ster

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/saki007ster
